name: Bump crates

inputs:
  version:
    required: true
  live-run:
    required: false
  branch:
    required: true
  repo:
    required: true
  path:
    required: false
  toolchain:
    required: false
  github-token:
    required: true
  bump-deps-pattern:
    description: "Multiline list of regular expressions for dependencies to bump (one per line)"
    required: false
  bump-deps-version:
    description: "Multiline list of versions, matching bump-deps-patterns (one per line)"
    required: false
  bump-deps-branch:
    required: false

runs:
  using: node20
  main: ../dist/bump-crates-main.mjs
