name: Publish crates (Cargo)

inputs:
  live-run:
    required: true
  branch:
    required: true
  repo:
    required: true
  submodule-path:
    required: false
  github-token:
    required: true
  crates-io-token:
    required: false
  artifactory-token:
    required: false
  artifactory-index:
    required: false
  unpublished-deps-patterns:
    required: false
  unpublished-deps-repos:
    required: false
  publication-test:
    required: false

runs:
  using: node20
  main: ../dist/publish-crates-cargo-main.mjs
