name: Release crates (Debian)

on:
  workflow_call:
    inputs:
      live-run:
        type: boolean
        required: true
      repo:
        type: string
        required: true
      version:
        type: string
        required: true
      branch:
        type: string
        required: true
      installation-test:
        type: boolean
        required: false
        default: true
      no-build:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      live-run:
        type: boolean
        required: true
      repo:
        type: string
        required: true
      version:
        type: string
        required: true
      branch:
        type: string
        required: true
      installation-test:
        type: boolean
        required: false
        default: true
      no-build:
        type: boolean
        required: false
        default: false

jobs:
  build:
    if: ${{ !inputs.no-build }}
    uses: eclipse-zenoh/ci/.github/workflows/build-crates-debian.yml@a1e923d376b4b676a740b245541203eba2f9f507
    with:
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      branch: ${{ inputs.branch }}
    secrets: inherit

  publish:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: eclipse-zenoh/ci/publish-crates-debian@a1e923d376b4b676a740b245541203eba2f9f507
        with:
          live-run: ${{ inputs.live-run }}
          version: ${{ inputs.version }}
          installation-test: ${{ inputs.installation-test }}
          ssh-host: genie.zenoh@projects-storage.eclipse.org
          ssh-host-path: /home/data/httpd/download.eclipse.org/zenoh/debian-repo
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          repo: ${{ inputs.repo }}
