name: Release crates (Cargo)

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      live-run:
        type: string
        required: true
      branch:
        type: string
        required: true
      unpublished-deps-patterns:
        type: string
        required: false
      unpublished-deps-repos:
        type: string
        required: false
      publication-test:
        type: boolean
        required: false
        default: true
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
      live-run:
        type: string
        required: true
      branch:
        type: string
        required: true
      unpublished-deps-patterns:
        type: string
        required: false
      unpublished-deps-repos:
        type: string
        required: false
      publication-test:
        type: boolean
        required: false
        default: true

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: eclipse-zenoh/ci/publish-crates-cargo@main
        with:
          repo: ${{ inputs.repo }}
          live-run: ${{ inputs.live-run }}
          branch: ${{ inputs.branch }}
          unpublished-deps-patterns: ${{ inputs.unpublished-deps-patterns }}
          unpublished-deps-repos: ${{ inputs.unpublished-deps-repos }}
          github-token: ${{ secrets.BOT_TOKEN_WORKFLOW }}
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
          publication-test: ${{ inputs.publication-test }}
