name: Tag crates

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      dry-run:
        type: boolean
        required: true
      version:
        type: string
        required: true
      inter-deps-pattern:
        type: string
        required: true
      inter-deps-version:
        type: string
        required: false
    outputs:
      branch:
        value: ${{ jobs.tag-crates.outputs.branch }}
      version:
        value: ${{ jobs.tag-crates.outputs.version }}
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
      dry-run:
        type: boolean
        required: true
      version:
        type: string
        required: true
      inter-deps-pattern:
        type: string
        required: true
      inter-deps-version:
        type: string
        required: false

jobs:
  tag-crates:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag-crates.outputs.version }}
      branch: ${{ steps.tag-crates.outputs.branch }}
    steps:
      - id: tag-crates
        uses: eclipse-zenoh/ci/tag-crates@main
        with:
          repo: ${{ inputs.repo }}
          dry-run: ${{ inputs.dry-run }}
          version: ${{ inputs.version }}
          inter-deps-pattern: ${{ inputs.inter-deps-pattern }}
          inter-deps-version: ${{ inputs.inter-deps-version }}
          actor-name: eclipse-zenoh-bot
          actor-email: eclipse-zenoh-bot@users.noreply.github.com
          github-token: ${{ secrets.BOT_TOKEN_WORKFLOW }}
