name: Yank crates

on:
  workflow_dispatch:
    inputs:
      crates:
        type: string
        description: Space separated list of crates to yank
        required: true
      version:
        type: string
        description: The version to yank
        required: true

defaults:
  run:
    shell: bash

jobs:
  yank-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Yank crates
        env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          for crate in ${{ inputs.crates }};
            do cargo yank $crate --version ${{ inputs.version }};
          done;
